name: Test, Build and Release apk
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build APK
    steps:
      - uses: actions/checkout@v1
      - name: Flutter action
        uses: subosito/flutter-action@v1.1.1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk --debug --split-per-abi
      - name: Create a Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*.apk"
